def generate_smr_report(case):
    """
    Compatible with 8-column cases table
    """

    case_id = case[0]
    property_id = case[1]
    amount = case[2]
    risk_score = case[3]
    risk_level = case[4]
    created = case[5]
    user = case[6]
    status = case[7]

    risk_band = "LOW"
    if risk_score >= 70:
        risk_band = "HIGH"
    elif risk_score >= 40:
        risk_band = "MEDIUM"

    report = f"""
AUSTRAC SUSPICIOUS MATTER REPORT (DRAFT)

CASE ID: {case_id}

PROPERTY:
{property_id}

TRANSACTION:
Amount: ${amount}

RISK ASSESSMENT:
- Risk Score: {risk_score}
- Risk Level: {risk_level}
- Risk Band: {risk_band}

CASE STATUS:
{status}

ANALYSIS:
This case was generated through automated risk scoring.

No additional CDD attributes (PEP, sanctions, etc.) are stored in the current case schema.

The case is classified as {risk_band.lower()} risk.

RECOMMENDATION:
{"ESCALATE TO SMR SUBMISSION" if risk_score >= 70 else "Continue monitoring under standard compliance procedures"}

Generated by: {user}
Created: {created}

END OF REPORT
"""
    return report
